<?php

return [
    // Asia
    'IN' => 'INR',
    'BD' => 'BDT',
    'PK' => 'PKR',
    'LK' => 'LKR',
    'NP' => 'NPR',
    'BT' => 'BTN',
    'ID' => 'IDR',
    'MY' => 'MYR',
    'SG' => 'SGD',
    'PH' => 'PHP',
    'TH' => 'THB',
    'VN' => 'VND',
    'JP' => 'JPY',
    'KR' => 'KRW',
    'HK' => 'HKD',
    'MO' => 'MOP',
    'TW' => 'TWD',
    'CN' => 'CNY',
    'KH' => 'KHR',
    'BN' => 'BND',

    // Middle East
    'AE' => 'AED',
    'SA' => 'SAR',
    'QA' => 'QAR',
    'OM' => 'OMR',
    'KW' => 'KWD',
    'BH' => 'BHD',
    'IL' => 'ILS',
    'JO' => 'JOD',

    // Europe
    'GB' => 'GBP',
    'IE' => 'EUR',
    'FR' => 'EUR',
    'DE' => 'EUR',
    'IT' => 'EUR',
    'ES' => 'EUR',
    'PT' => 'EUR',
    'NL' => 'EUR',
    'BE' => 'EUR',
    'AT' => 'EUR',
    'CH' => 'CHF',
    'SE' => 'SEK',
    'NO' => 'NOK',
    'DK' => 'DKK',
    'FI' => 'EUR',
    'PL' => 'PLN',
    'CZ' => 'CZK',
    'HU' => 'HUF',
    'RO' => 'RON',
    'BG' => 'BGN',
    'HR' => 'EUR',
    'GR' => 'EUR',
    'CY' => 'EUR',
    'MT' => 'EUR',
    'UA' => 'UAH',
    'RU' => 'RUB',

    // Americas
    'US' => 'USD',
    'CA' => 'CAD',
    'MX' => 'MXN',
    'BR' => 'BRL',
    'AR' => 'ARS',
    'CL' => 'CLP',
    'CO' => 'COP',
    'PE' => 'PEN',
    'UY' => 'UYU',
    'PY' => 'PYG',
    'BO' => 'BOB',
    'CR' => 'CRC',
    'GT' => 'GTQ',
    'HN' => 'HNL',
    'NI' => 'NIO',
    'SV' => 'USD',
    'PA' => 'PAB',
    'DO' => 'DOP',
    'JM' => 'JMD',
    'BS' => 'BSD',
    'BB' => 'BBD',

    // Africa
    'ZA' => 'ZAR',
    'NG' => 'NGN',
    'KE' => 'KES',
    'GH' => 'GHS',
    'TZ' => 'TZS',
    'UG' => 'UGX',
    'RW' => 'RWF',
    'ZM' => 'ZMW',
    'BW' => 'BWP',
    'CM' => 'XAF',

    // Oceania
    'AU' => 'AUD',
    'NZ' => 'NZD',

    // Territories
    'BM' => 'BMD',
    'AW' => 'AWG',
    'VG' => 'USD',
    'AS' => 'USD',
];

